### ISSUE TITLE
TS2790 [ERROR]: The operand of a 'delete' operator must be optional.

### ISSUE THREAD

**Issue by vicky-gonsalves** [eveningkid/denodb#110]
I am using following version of deno with denodb v `1.0.8` and trying to use mongoDB connection.

```
deno --version
deno 1.3.3
v8 8.6.334
typescript 4.0.2
```

when running it throws following error:

```
error: TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.conn;
           ~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:612:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufReader;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:613:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.bufWriter;
           ~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:614:12

TS2790 [ERROR]: The operand of a 'delete' operator must be optional.
    delete this.packetWriter;
           ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/postgres@v0.4.3/connection.ts:615:12

Found 4 errors.
```

Is there any clue what is wrong? 
I further found that this works well with lower deno versions than 1.3.2

**Comment by lazcanocode** [comment]
Same problem could you check this [commet](https://github.com/eveningkid/denodb/issues/111#issuecomment-689217768)

**Comment by eveningkid** [comment]
Hi Vicky,

Seems like the error is similar to #111 (cool number :)) so let's have no duplicates.

Maybe subscribe to that issue so you get updates later on.

Have a great day
