### ISSUE TITLE
this._models.forEach is not a function

### ISSUE THREAD

**Issue by Danieliessen** [eveningkid/denodb#118]
TypeError: this._models.forEach is not a function
    at Database.link (database.ts:142:18)
    at DatabaseAccess.init (data.ts:11:17)
    at postRegister (routes.ts:86:18)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
    at async page404MiddleWare (page404MiddleWare.ts:5:1)
    at async dispatch (middleware.ts:41:7)
    at async staticFileMiddleWare (staticFileMiddleWare.ts:11:9)
    at async dispatch (middleware.ts:41:7)

**Comment by Danieliessen** [comment]
Works now, just reloaded cache, sorry! 😄
