### ISSUE TITLE
Many-To-Many relationship sqlite: SqliteError: table table1_table2 has no column named table1Id

### ISSUE THREAD

**Issue by tofi92** [eveningkid/denodb#124]
Hi,
when using denodb with sqlite and many-to-many relationships I get the following error when executing this query:

```
let key: number = 1;
await table1.where("id", key).table2s();
SqliteError: table table1_table2 has no column named table1Id
at DB._error (db.ts:238:12)
    at DB.query (db.ts:116:18)
    at sqlite3-connector.ts:55:37
    at Array.map (<anonymous>)
    at SQLite3Connector.query (sqlite3-connector.ts:54:32)
    at async Database.query (database.ts:161:21)
```

When looking at the sqlite file, I can see that the column names are "table1_id" and "table2_id" with an underscore.
My primary keys are numbers, if this is any help.

**Comment by stillalivx** [comment]
Hey man! Can you show me the model of the table1 and table2?

**Comment by tofi92** [comment]
Sorry, was away for the weekend :)
Here they are:
Table1
```
import { DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";
import Recipe from "./Recipe.ts";
export default class Cookbook extends Model {
  static table = "cookbooks";
  static timestamps = true;
  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
      type: DataTypes.INTEGER,
      unique: true,
    },
    title: DataTypes.STRING,
    titleAnchor: DataTypes.STRING,
    description: DataTypes.STRING,
    userId: DataTypes.STRING,
  };
  static recipes() {
    return this.hasMany(Recipe);
  }

  id!: number;
  title!: string;
  titleAnchor!: string;
  description!: string;
  userId!: string;
}

```
Table2
```
import { DataTypes, Model } from "https://deno.land/x/denodb/mod.ts";
import Cookbook from "./Cookbook.ts";
export default class Recipe extends Model {
  static table = "recipes";
  static timestamps = true;
  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: true,
      type: DataTypes.INTEGER,
      unique: true,
    },
    title: DataTypes.STRING,
    description: DataTypes.STRING,
    preparation: DataTypes.STRING,
    preparationTimeMinutes: DataTypes.INTEGER,
    preparationDifficulty: DataTypes.INTEGER,
    userId: DataTypes.STRING,
  };
  static cookbooks() {
    return this.hasMany(Cookbook);
  }

  id!: number;
  title!: string;
  description!: string;
  preparation!: string;
  preparationTimeMinutes!: number;
  preparationDifficulty!: number;
  userId!: string;
}
```
The relationship:
```
import { Relationships } from "https://deno.land/x/denodb/mod.ts";
import Cookbook from "./Cookbook.ts";
import Recipe from "./Recipe.ts";

export const recipeList = Relationships.manyToMany(Cookbook, Recipe);
```
How they are linked:
```
import Cookbook from "./entities/Cookbook.ts";
import Recipe from "./entities/Recipe.ts";
import { recipeList } from "./entities/RecipeList.ts";
db.link([recipeList, Cookbook, Recipe]);
```

Hope that helps!

**Comment by eveningkid** [comment]
Good to see #131 fixed this issue :)

Thank you for your contribution!
