### ISSUE TITLE
Many to many official example error

### ISSUE THREAD

**Issue by sqllyw** [eveningkid/denodb#129]
Hi,
new to denodb, trying out the official [many to many example](https://eveningkid.github.io/denodb-docs/docs/guides/many-to-many#example), got following error, any idea? thanks
````
Uncaught SqliteError: no such column: businesses_owners.ownerId
    return new SqliteError(msg, code);
  at DB._error (db.ts:238:12)
    at DB.query (db.ts:116:18)
    at sqlite3-connector.ts:55:37
    at Array.map (<anonymous>)
    at SQLite3Connector.query (sqlite3-connector.ts:54:32)
    at async Database.query (database.ts:161:21)
````

**Comment by techtastet** [comment]
Hi @sqllyw ! 😄 

Can you give me what the `deno --version` command returns to you?
Mine returns for example:
- deno 1.4.4
- v8 8.7.75
- typescript 4.0.3


And can you test the following code and tell me if it works :
```typescript
import {
  Database,
  DataTypes,
  Model,
  Relationships,
} from "https://raw.githubusercontent.com/eveningkid/denodb/b98aac4bd331ba145467a825d879c7cc80d6002d/mod.ts";
// For the cache

const db = new Database("sqlite3", {
  filepath: "./database.sqlite",
});

class Owner extends Model {
  static table = "owners";

  static fields = {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    name: DataTypes.STRING,
  };

  static businesses() {
    return this.hasMany(Business);
  }
}

class Business extends Model {
  static table = "businesses";

  static fields = {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    name: DataTypes.STRING,
  };

  static owners() {
    return this.hasMany(Owner);
  }
}

const BusinessOwner = Relationships.manyToMany(Business, Owner);

db.link([BusinessOwner, Business, Owner]);

await db.sync({ drop: true });

await Owner.create([
  {
    id: "1",
    name: "John",
  },
  {
    id: "2",
    name: "Sarah",
  },
]);

await Business.create([
  {
    id: "1",
    name: "Parisian Café",
  },
  {
    id: "2",
    name: "Something About Us",
  },
]);

await BusinessOwner.create([
  { businessId: "1", ownerId: "1" },
  { businessId: "1", ownerId: "2" },
  { businessId: "2", ownerId: "1" },
]);

await Owner.where("id", "1").businesses();
await Owner.where("id", "2").businesses();
console.log(await Business.where("id", "2").owners());

await db.close();
```

**Comment by eveningkid** [comment]
Hi,

I believe the error came from that camel case/snake case issue we had till this day.

It is now all fixed and should solve your issue!

Thanks Thomas for helping out, I really appreciate it :)

**Comment by buckley310** [comment]
Thomas's example above works for me, however when I try the same code, except changing the URL from b98aac4bd331ba145467a825d879c7cc80d6002d to 9b2be1b1de5935c6720e2e0c4915d673148d0a3e (current master) I get the same error `no such column: businesses_owners.ownerId`. Am I missing something or is this still an issue?

**Comment by devingfx** [comment]
Hi!
This is still an issue... please reopen it !
At least with SQLite3 connector.
I looked at the code and can't find the error BTW, the fields are been asked to be camelCase at creation but with the external SQLite viewer I can see it's created with snake_case.

I could work around by passing a `RelationshipOptions` setting the sanle_case keys though...

```js
// ...
const UserRole = Relationships.manyToMany( User, Role, {primaryKey: 'user_id', foreignKey: 'role_id'} )

db.link([ User, Role, UserRole ])
await db.sync({drop:true})
// ...
await UserRole.create([
	{ user_id: 1, role_id: 2 },
	{ user_id: 2, role_id: 3 },
	{ user_id: 3, role_id: 1 },
])
```
