### ISSUE TITLE
Typescript errors in DenoDb 1.0.10

### ISSUE THREAD

**Issue by biggledfred** [eveningkid/denodb#132]
Just tried to cache the new version of DenoDb (v1.0.10) and I get the following error:

`error: TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
        prev[alias] = this.formatFieldNameToDatabase(fullName);
        ~~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/translators/sql-translator.ts:230:9

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
                prev[field] = orderDirection === "asc" ? 1 : -1;
                ~~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/connectors/mongodb-connector.ts:262:17

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
        prev[clientFieldName] = databaseFieldName;
        ~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/database.ts:198:9

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
        prev[`${table}.${clientFieldName}`] = `${table}.${databaseFieldName}`;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/database.ts:199:9

TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
        prev[this._formatField(fieldMatching, fieldName) as string] = value;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/model.ts:194:9

TS2339 [ERROR]: Property 'primaryKey' does not exist on type 'RelationshipOptions | undefined'.
    const { primaryKey, foreignKey } = options;
            ~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/relationships.ts:24:13

TS2339 [ERROR]: Property 'foreignKey' does not exist on type 'RelationshipOptions | undefined'.
    const { primaryKey, foreignKey } = options;
                        ~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/relationships.ts:24:25

TS2339 [ERROR]: Property 'primaryKey' does not exist on type 'RelationshipOptions | undefined'.
    const { primaryKey, foreignKey } = options;
            ~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/relationships.ts:34:13

TS2339 [ERROR]: Property 'foreignKey' does not exist on type 'RelationshipOptions | undefined'.
    const { primaryKey, foreignKey } = options;
                        ~~~~~~~~~~
    at https://deno.land/x/denodb@v1.0.10/lib/relationships.ts:34:25

Found 9 errors.`

- Tried both Deno 1.2.x and 1.4.x. Neither work.
- No issue with denodb version 1.0.9

I'll see if I have time to fix errors above.

Regards

**Comment by Danieliessen** [comment]
Same
