### ISSUE TITLE
Linking models to database via an array

### ISSUE THREAD

**Issue by yababay** [eveningkid/denodb#14]
Hi Arnaud.

I am trying to use linking models to database via an array:

```

class Manufacturers extends Model {
    static table = 'manufacturers';
    static timestamps = true;
    static fields = {
        id: {
            primaryKey: true,
            autoIncrement: true,
        },
        manufacturer: DATA_TYPES.STRING,
    }
}

class Parts extends Model {
    static table = 'parts';
    static timestamps = true;
    static fields = {
        id: {
            primaryKey: true,
            autoIncrement: true,
        },
        part: DATA_TYPES.STRING,
    }
}

db.link([Manufacturers, Parts])
await db.sync({ drop: true });

```
And I get an error message:

```
error: Uncaught RangeError: Invalid typed array length: -4
    const msgBody = new Uint8Array(msgLength);
                    ^
    at new Uint8Array (<anonymous>)
    at Connection.readMessage (https://deno.land/x/postgres/connection.ts:104:21)
    at async Connection.startup (https://deno.land/x/postgres/connection.ts:154:11)
    at async Client.connect (https://deno.land/x/postgres/client.ts:14:5)
    at async PostgresConnector._makeConnection (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:38:5)
    at async PostgresConnector.query (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:43:5)
    at async ModelInitializer.init (https://deno.land/x/denodb/lib/model-initializer.ts:26:7)
    at async Function._createInDatabase (file:///home/3f-lab/_reusable/denodb/lib/model.ts:75:5)
    at async Promise.all (index 1)
```
But when I do 

```
db.link([Manufacturers])
db.link([Parts])
await db.sync({ drop: true });
```

the code works OK.

Could you help to correct this?

**Comment by eveningkid** [comment]
Hey Yababay,

Thanks for letting me know. I wonder how did it work till now, but your example wouldn't run on my computer.

I think I found the issue and updated with #15.

If you can run `deno run --reload ...` and let me know if that fixed your issue, that would be great :)

Keep in touch

**Comment by yababay** [comment]
Thank you, Arnaud, the option `deno run --reload ...` did help.
