### ISSUE TITLE
Uncaught TypeError when adding table with non-autoincrementing primary key

### ISSUE THREAD

**Issue by Coteh** [eveningkid/denodb#16]
I am trying to add a model with a primary key that's set manually rather than autoincrementing.
My schema looks something like this:
```
export default class NetInfoModel extends Model {
  static table = "net_info";

  static fields = {
    id: {
      primaryKey: true,
      autoIncrement: false,
    },
    name: DATA_TYPES.STRING,
  };
}
```
When I try to add this model using `db.link` I get the following error:
```
error: Uncaught TypeError: table[type] is not a function
      instruction = table[type](...fieldNameArgs);
                               ^
    at addFieldToSchema (https://deno.land/x/denodb/lib/helpers/fields.ts:30:32)
    at TableBuilder._fn (https://deno.land/x/denodb/lib/translators/sql-translator.ts:107:15)
    at TableBuilder.toSQL (https://deno.land/x/dex/lib/schema/tablebuilder.js:45:12)
    at SchemaCompiler_SQLite3.createTableIfNotExists (https://deno.land/x/dex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (https://deno.land/x/dex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (https://deno.land/x/dex/lib/schema/builder.js:81:43)
    at SchemaBuilder.Target.toQuery (https://deno.land/x/dex/lib/interface.js:9:21)
    at SchemaBuilder.toString (https://deno.land/x/dex/lib/schema/builder.js:77:15)
    at SQLTranslator.translateToQuery (https://deno.land/x/denodb/lib/translators/sql-translator.ts:170:25)
    at SQLite3Connector.query (https://deno.land/x/denodb/lib/connectors/sqlite3-connector.ts:33:36)
```
Here's the line where it throws the exception:
https://github.com/eveningkid/denodb/blob/master/lib/helpers/fields.ts#L30
I am not really sure what's going on in this line. I am going to have another look in a bit, but so far I am not really sure if this is expected behaviour or not and wanted to confirm.

**Comment by eveningkid** [comment]
Hey James,

Thanks for raising this issue.

In this case, you simply need to omit `autoIncrement` (it will be set to `false` by default), and define a type on your field. The error simply says you have no `type` for this field.

```typescript
static fields = {
  id: {
    primaryKey: true,
    type: DATA_TYPES.INTEGER, // or `STRING`, up to you
  },
  name: DATA_TYPES.STRING,
};
```

Let me know if that does it for you.

Keep in touch

**Comment by Coteh** [comment]
Doh! I should have realized! Also just took another look at the flow of the code and it makes sense now why that error occurred. Thanks for the help Arnaud! I will close this now.
