### ISSUE TITLE
Unhandled notice

### ISSUE THREAD

**Issue by saydus** [eveningkid/denodb#166]
I am not sure what exactly is causing the issue here, but I also get the TODO messages in console output. 
```
TODO: handle notice
TODO: handle notice
TODO: handle notice
TODO: handle notice
TODO: handle notice
error: Uncaught (in promise) PostgresError: relation "notes" does not exist
  return new PostgresError(errorFields);
         ^
    at parseError (error.ts:106:10)
    at Connection._processError (connection.ts:434:19)
    at Connection._simpleQuery (connection.ts:340:22)
    at async Connection.query (connection.ts:546:16)
    at async Client.query (client.ts:25:12)
    at async PostgresConnector.query (postgres-connector.ts:60:22)
    at async Database.query (database.ts:164:21)
    at async Function.createTable (model.ts:161:5)
    at async Database.sync (database.ts:134:7)
    at async app.ts:15:1
```

**Comment by eveningkid** [comment]
Hey Saydolimkhon,

Thank you for raising this issue and the long wait.

It seems to have been fixed since I couldn't find any TODO logs from the Postgres driver code and denodb.

Good day :)
