### ISSUE TITLE
Connection to ElephantSQL failing

### ISSUE THREAD

**Issue by saydus** [eveningkid/denodb#169]
The application is connecting fine locally, but whenever I try to use a remote Postgres as a service (ElephantSQL), I get the following error:

```
error: Uncaught (in promise) Error: Unknown response for startup: E
          throw new Error(`Unknown response for startup: ${msg.type}`);
                ^
    at Connection.startup (connection.ts:173:17)
    at async Client.connect (client.ts:14:5)
    at async PostgresConnector._makeConnection (postgres-connector.ts:39:5)
    at async PostgresConnector.query (postgres-connector.ts:57:5)
    at async Database.query (database.ts:164:21)
    at async Function.createTable (model.ts:161:5)
    at async Database.sync (database.ts:134:7)
    at async app.ts:17:1
```

I am not sure what exactly is causing it to fail on remote connections.

**Comment by edimoldovan** [comment]
I am getting the same error with the Postres app on mac OS. Here are the steps I followed:

- Initialize database const db = new Database({ dialect: 'postgres', debug: true }, {...}); in a separate file, then doing export default db
- in my model definiton file import db from "../models/database.ts"; then define the model, then link the model, then sync the model, then try an insert.

It seems to fail at sync.

**Comment by rluvaton** [comment]
@saydus @edimoldovan There is a new version published just now, can you tell me if the new version fixes your issue

**The new version has breaking changes, head over to [connectors migration docs](https://github.com/eveningkid/denodb/blob/master/docs/v1.0.21-migration/connectors.md) to help with the migration**

**Comment by saydus** [comment]
@rluvaton I changed it to use the latest version, used a connector, but it still fails to connect.
```
error: Uncaught (in promise) Error: Unknown response for startup: E
          throw new Error(`Unknown response for startup: ${msg.type}`);
                ^
    at Connection.startup (connection.ts:173:17)
    at async Client.connect (client.ts:14:5)
    at async PostgresConnector._makeConnection (postgres-connector.ts:42:5)
    at async PostgresConnector.query (postgres-connector.ts:60:5)
    at async Database.query (database.ts:227:21)
    at async Function.drop (model.ts:137:5)
    at async Database.sync (database.ts:192:9)
    at async app.ts:17:1
```

**Comment by rluvaton** [comment]
We are using this library [denodrivers/postgres](https://github.com/denodrivers/postgres) for interacting with Postgres and it seems like that your issue relates to their library https://github.com/denodrivers/postgres/issues/120. I hope they will fix it soon so this issue can be resolved

**Comment by saydus** [comment]
Thanks @rluvaton. I also hope they fix it soon - it's been open since May 😔
