### ISSUE TITLE
Postgres Error: Unknown auth message code 1375731712

### ISSUE THREAD

**Issue by autsada** [eveningkid/denodb#201]
Hi,

I ran into this below error when I have multiple requests to different tables.

```
Error: Unknown auth message code 1375731712
    at Connection.handleAuth (connection.ts:197:15)
    at Connection.startup (connection.ts:155:16)
    at async Client.connect (client.ts:14:5)
    at async PostgresConnector._makeConnection (postgres-connector.ts:42:5)
    at async PostgresConnector.query (postgres-connector.ts:60:5)
    at async Database.query (database.ts:226:21)
    at async Function._runQuery (model.ts:217:21)
    at async listProducts (public.ts:15:22)
    at async dispatch (middleware.ts:41:7)
    at async dispatch (middleware.ts:41:7)
```

It may relates to [the issue#242](https://github.com/denodrivers/postgres/issues/242) of [deno-postgres](https://deno.land/x/postgres@v0.7.1).

**Comment by eveningkid** [comment]
Hey ausada,

Thanks for the heads up.

I upgraded to the latest version of `deno-postgres@v0.11.1` earlier today.

If you're still facing this issue, you'll have to follow the progress on their side.

I'm sorry I can't help on this one, let's hope for the best :)

Have a great day

**Comment by autsada** [comment]
Hi @eveningkid 

Thank you very much. I will try it again.

Have a nice day.
