### ISSUE TITLE
need upsert or raw queries

### ISSUE THREAD

**Issue by samhess** [eveningkid/denodb#211]
MySQL - Implemented with ON DUPLICATE KEY UPDATE
PostgreSQL - Implemented with ON CONFLICT DO UPDATE

Links:
https://sequelize.org/master/manual/raw-queries.html
https://sequelize.org/master/class/lib/model.js~Model.html
http://knexjs.org/#Schema-raw

**Comment by eveningkid** [comment]
Hey Samuel,

You can already run raw queries:

```js
const db = new Database(connector);
await db.query('SELECT * FROM users');
```

I hope this will allow you to do what you want :)

Good day

**Comment by cyzhzhd** [comment]
> Hey Samuel,
> 
> You can already run raw queries:
> 
> ```js
> const db = new Database(connector);
> await db.query('SELECT * FROM users');
> ```
> 
> I hope this will allow you to do what you want :)
> 
> Good day

This isn't working on me

env: DenoDB version 1.0.31

```
ts warning:  Argument of type 'string' is not assignable to parameter of type 'QueryDescription'.
      const result = await db.query('select * from data');

error: PostgresError: syntax error at or near "function"
    at parseError (https://deno.land/x/postgres@v0.4.6/error.ts:106:10)
    at Connection._processError (https://deno.land/x/postgres@v0.4.6/connection.ts:434:19)
    at Connection._simpleQuery (https://deno.land/x/postgres@v0.4.6/connection.ts:298:20)
    at async Connection.query (https://deno.land/x/postgres@v0.4.6/connection.ts:546:16)
    at async Client.query (https://deno.land/x/postgres@v0.4.6/client.ts:25:12)
    at async PostgresConnector.query (https://deno.land/x/denodb@v1.0.30/lib/connectors/postgres-connector.ts:63:22)
    at async Database.query (https://deno.land/x/denodb@v1.0.30/lib/database.ts:234:21)
    at async findByKeyword (file:///Users/ekwon/dev/search-api/src/services/search.service.ts:12:22)
    at async getSearchResult (file:///Users/ekwon/dev/search-api/src/controllers/search.controller.ts:17:18)
    at async dispatch (https://deno.land/x/oak@v7.7.0/middleware.ts:41:7)
```

**Comment by acrodrig** [comment]
I have the same issue (i.e. "Argument of type 'string' is not assignable to parameter of type 'QueryDescription'."). Can you help?

**Comment by KimEJ** [comment]
korean sorry :(

더러운 방법이지만 connector 에서 직접 호출할 수 있습니다.

```javascript
const users = await connector._client.query('SELECT * FROM users;');
```

try it

**Comment by samhess** [comment]
no worries, I habe been out of deno for a long time

Am Fr., 7. Juni 2024 um 06:31 Uhr schrieb 김어진 ***@***.***>:
