### ISSUE TITLE
Error importing another module

### ISSUE THREAD

**Issue by yeop-sang** [eveningkid/denodb#213]
I downloaded denodb.

But there was an error about https://raw.githubusercontent.com/denjucks/dex/master/mod.ts was not found at https://deno.land/x/denodb@v1.0.23/deps.ts:3:0.
How can I fix that?

I copied the log while downloading the package.
```
Download https://deno.land/x/denodb/mod.ts
Warning Implicitly using latest version (v1.0.23) for https://deno.land/x/denodb/mod.ts
Download https://deno.land/x/denodb@v1.0.23/mod.ts
Download https://deno.land/x/denodb@v1.0.23/lib/connectors/postgres-connector.ts
Download https://deno.land/x/denodb@v1.0.23/lib/connectors/sqlite3-connector.ts
Download https://deno.land/x/denodb@v1.0.23/lib/database.ts
Download https://deno.land/x/denodb@v1.0.23/lib/data-types.ts
Download https://deno.land/x/denodb@v1.0.23/lib/model.ts
Download https://deno.land/x/denodb@v1.0.23/lib/connectors/factory.ts
Download https://deno.land/x/denodb@v1.0.23/lib/connectors/mongodb-connector.ts
Download https://deno.land/x/denodb@v1.0.23/lib/connectors/mysql-connector.ts
Download https://deno.land/x/denodb@v1.0.23/lib/relationships.ts
Download https://deno.land/x/denodb@v1.0.23/lib/connectors/connector.ts
Download https://deno.land/x/denodb@v1.0.23/lib/query-builder.ts
Download https://deno.land/x/denodb@v1.0.23/deps.ts
Download https://deno.land/x/denodb@v1.0.23/lib/translators/sql-translator.ts
Download https://deno.land/x/denodb@v1.0.23/lib/translators/translator.ts
Download https://deno.land/x/denodb@v1.0.23/lib/model-pivot.ts
Download https://deno.land/x/denodb@v1.0.23/lib/helpers/results.ts
Download https://deno.land/x/denodb@v1.0.23/lib/translators/basic-translator.ts
Download https://deno.land/x/sqlite@v2.3.1/mod.ts
Download https://raw.githubusercontent.com/denjucks/dex/master/mod.ts
Download https://deno.land/x/colorlog@v1.0/mod.ts
Download https://deno.land/x/mongo@v0.20.0/mod.ts
Download https://deno.land/x/mongo@v0.20.0/src/database.ts
Download https://deno.land/x/case/mod.ts
Download https://deno.land/x/mysql/mod.ts
Download https://deno.land/x/denodb@v1.0.23/lib/helpers/fields.ts
Download https://deno.land/x/mongo@v0.20.0/src/protocol/mod.ts
Download https://deno.land/x/mongo@v0.20.0/src/types.ts
Download https://deno.land/x/mongo@v0.20.0/src/collection/mod.ts
Download https://deno.land/x/sqlite@v2.3.1/src/db.ts
Download https://deno.land/x/sqlite@v2.3.1/src/constants.ts
Download https://deno.land/x/sqlite@v2.3.1/src/rows.ts
Warning Implicitly using latest version (v2.1.0) for https://deno.land/x/case/mod.ts
Download https://deno.land/x/case@v2.1.0/mod.ts
Warning Implicitly using latest version (v2.8.0) for https://deno.land/x/mysql/mod.ts
Download https://deno.land/x/mysql@v2.8.0/mod.ts
Download https://deno.land/x/mongo@v0.20.0/src/client.ts
Download https://deno.land/x/mysql@v2.8.0/src/client.ts
Download https://deno.land/x/mysql@v2.8.0/src/logger.ts
Download https://deno.land/x/mysql@v2.8.0/deps.ts
Download https://deno.land/x/mysql@v2.8.0/src/connection.ts
Download https://deno.land/x/mysql@v2.8.0/src/packets/builders/auth.ts
Download https://deno.land/x/mysql@v2.8.0/src/constant/packet.ts
Download https://deno.land/x/mysql@v2.8.0/src/auth_plugin/index.ts
Download https://deno.land/x/mysql@v2.8.0/src/packets/packet.ts
Download https://deno.land/x/mysql@v2.8.0/src/constant/errors.ts
Download https://deno.land/x/mysql@v2.8.0/src/packets/parsers/err.ts
Download https://deno.land/x/mysql@v2.8.0/src/packets/parsers/result.ts
Download https://deno.land/x/mysql@v2.8.0/src/packets/builders/query.ts
Download https://deno.land/x/mysql@v2.8.0/src/packets/parsers/handshake.ts
Download https://deno.land/x/mysql@v2.8.0/src/pool.ts
Download https://deno.land/x/mysql@v2.8.0/src/constant/charset.ts
Download https://deno.land/x/mysql@v2.8.0/src/auth.ts
Download https://deno.land/x/mysql@v2.8.0/src/buffer.ts
Download https://deno.land/x/mysql@v2.8.0/src/constant/capabilities.ts
Download https://deno.land/x/mysql@v2.8.0/src/auth_plugin/caching_sha2_password.ts
Download https://deno.land/x/mysql@v2.8.0/src/constant/mysql_types.ts
Download https://deno.land/x/mysql@v2.8.0/src/deferred.ts
Download https://deno.land/x/mysql@v2.8.0/src/util.ts
Download https://deno.land/x/mysql@v2.8.0/src/auth_plugin/crypt.ts
Download https://deno.land/x/mongo@v0.20.0/deps.ts
Download https://deno.land/x/mongo@v0.20.0/src/collection/collection.ts
Download https://deno.land/x/mongo@v0.20.0/src/protocol/protocol.ts
Download https://deno.land/x/mongo@v0.20.0/src/protocol/header.ts
Download https://deno.land/x/mongo@v0.20.0/src/protocol/message.ts
Download https://deno.land/x/mongo@v0.20.0/src/protocol/cursor.ts
Download https://deno.land/x/god_crypto@v0.2.0/mod.ts
Download https://deno.land/x/god_crypto@v0.2.0/rsa.ts
Download https://deno.land/x/god_crypto@v0.2.0/src/basic_encoding_rule.ts
Download https://deno.land/x/god_crypto@v0.2.0/src/rsa.ts
Download https://deno.land/x/god_crypto@v0.2.0/src/helper.ts
Download https://deno.land/x/god_crypto@v0.2.0/src/math.ts
Download https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts
Download https://deno.land/x/god_crypto@v0.2.0/src/primitives.ts
Download https://deno.land/x/sqlite@v2.3.1/src/row_objects.ts
Download https://deno.land/x/sqlite@v2.3.1/src/error.ts
Download https://deno.land/x/sqlite@v2.3.1/src/wasm.ts
Download https://deno.land/x/sqlite@v2.3.1/build/sqlite.js
Download https://deno.land/x/case@v2.1.0/normalCase.ts
Download https://deno.land/x/case@v2.1.0/pathCase.ts
Download https://deno.land/x/case@v2.1.0/upperFirstCase.ts
Download https://deno.land/x/case@v2.1.0/sentenceCase.ts
Download https://deno.land/x/case@v2.1.0/titleCase.ts
Download https://deno.land/x/case@v2.1.0/pascalCase.ts
Download https://deno.land/x/case@v2.1.0/paramCase.ts
Download https://deno.land/x/case@v2.1.0/camelCase.ts
Download https://deno.land/x/case@v2.1.0/snakeCase.ts
Download https://deno.land/x/case@v2.1.0/lowerCase.ts
Download https://deno.land/x/case@v2.1.0/lowerFirstCase.ts
Download https://deno.land/x/case@v2.1.0/swapCase.ts
Download https://deno.land/x/case@v2.1.0/upperCase.ts
Download https://deno.land/x/case@v2.1.0/constantCase.ts
Download https://deno.land/x/case@v2.1.0/headerCase.ts
Download https://deno.land/x/case@v2.1.0/dotCase.ts
Download https://deno.land/x/mongo@v0.20.0/src/utils/uri.ts
Download https://deno.land/std/hash/mod.ts
Download https://deno.land/x/mongo@v0.20.0/bson/mod.ts
Download https://deno.land/std@0.77.0/async/deferred.ts
Download https://deno.land/std@0.77.0/testing/asserts.ts
Download https://deno.land/std@0.77.0/io/mod.ts
Download https://deno.land/x/mongo@v0.20.0/src/collection/commands/find.ts
Download https://deno.land/x/mongo@v0.20.0/src/collection/commands/aggregate.ts
Download https://deno.land/x/mongo@v0.20.0/src/collection/commands/update.ts
Download https://deno.land/x/mongo@v0.20.0/src/protocol/handshake.ts
Download https://deno.land/x/mongo@v0.20.0/src/error.ts
Download https://deno.land/x/mongo@v0.20.0/src/utils/bson.ts
Download https://deno.land/x/mongo@v0.20.0/src/utils/ns.ts
Warning Implicitly using latest version (0.91.0) for https://deno.land/std/hash/mod.ts
Download https://deno.land/std@0.91.0/hash/mod.ts
Download https://deno.land/x/case@v2.1.0/types.ts
Download https://deno.land/std@0.91.0/hash/_wasm/hash.ts
Download https://deno.land/std@0.91.0/hash/hasher.ts
Download https://deno.land/std@0.91.0/hash/_wasm/wasm.js
Download https://deno.land/std@0.91.0/encoding/hex.ts
Download https://deno.land/std@0.91.0/encoding/base64.ts
Download https://deno.land/x/case@v2.1.0/vendor/camelCaseRegexp.ts
Download https://deno.land/x/case@v2.1.0/vendor/camelCaseUpperRegexp.ts
Download https://deno.land/x/case@v2.1.0/vendor/nonWordRegexp.ts
Download https://deno.land/x/mongo@v0.20.0/bson/bson.d.ts
Download https://deno.land/std@0.77.0/io/writers.ts
Download https://deno.land/std@0.77.0/io/streams.ts
Download https://deno.land/std@0.77.0/io/readers.ts
Download https://deno.land/std@0.77.0/io/ioutil.ts
Download https://deno.land/std@0.77.0/testing/_diff.ts
Download https://deno.land/x/sqlite@v2.3.1/build/vfs.js
error: Import 'https://raw.githubusercontent.com/denjucks/dex/master/mod.ts' failed: 404 Not Found
    at https://deno.land/x/denodb@v1.0.23/deps.ts:3:0
```

**Comment by yeop-sang** [comment]
Sorry it is duplicated with  issue #209
