### ISSUE TITLE
SQLite complains that 'airportId' doesn't exist, expects 'airport_id'

### ISSUE THREAD

**Issue by gcocatre** [eveningkid/denodb#260]
In the documentation for the `leftJoin()` method, the following example is given:

```
await Flight.where(Flight.field('departure'), 'Paris')
  .leftJoin(Airport, Airport.field('id'), Flight.field('airportId'))
  .get();
```

But when I run that code with an SQLite database, SQLite throws an error:
```
SqliteError: no such column: flights.airportId
    at DB._error (https://deno.land/x/sqlite@v2.3.1/src/db.ts:289:12)
    at DB.query (https://deno.land/x/sqlite@v2.3.1/src/db.ts:124:18)
    at https://deno.land/x/denodb@v1.0.38/lib/connectors/sqlite3-connector.ts:58:37
    at Array.map (<anonymous>)
    at SQLite3Connector.query (https://deno.land/x/denodb@v1.0.38/lib/connectors/sqlite3-connector.ts:57:32)
    at Database.query (https://deno.land/x/denodb@v1.0.38/lib/database.ts:240:47)
    at Function._runQuery (https://deno.land/x/denodb@v1.0.38/lib/model.ts:228:42)
    at Function.get (https://deno.land/x/denodb@v1.0.38/lib/model.ts:407:17)
```

The following code works (changing `airportId` in camel case to `airport_id` in snake case):

```
await Flight.where(Flight.field('departure'), 'Paris')
  .leftJoin(Airport, Airport.field('id'), Flight.field('airport_id'))
  .get();
```

**Comment by stillalivx** [comment]
You are right! When you use Model.field method, you have to use snake case. @eveningkid, could we change this behavor to allow users use camel case. I think that we could keep consistant in the field's naming.
