### ISSUE TITLE
Nullable foreignkey

### ISSUE THREAD

**Issue by ddorstijn** [eveningkid/denodb#261]
Is there a way to add a "one to zero or one" relationship at the moment? It seems like the not null constraint is added automatically and there seems no way to go around it? I saw a closed issue about creating the relationship manually but I cannot find documentation on how to do this.

**Comment by stillalivx** [comment]
Hi, @ddorstijn. Is that the complete error's message? And if not. Could you show all the message in order to understand where is throwing the error?

**Comment by ddorstijn** [comment]
I assumed the error log would probably be related to the null constraint, so I thought it would not be of use. The full error message is as follows:

```
Error: Column 'family_id' cannot be null
    at PoolConnection.nextPacket (https://deno.land/x/mysql@v2.8.0/src/connection.ts:185:13)
    at async PoolConnection.execute (https://deno.land/x/mysql@v2.8.0/src/connection.ts:263:21)
    at async https://deno.land/x/mysql@v2.8.0/src/client.ts:97:14
    at async Client.useConnection (https://deno.land/x/mysql@v2.8.0/src/client.ts:107:14)
    at async Client.execute (https://deno.land/x/mysql@v2.8.0/src/client.ts:96:12)
    at async MySQLConnector.query (https://deno.land/x/denodb@v1.0.38/lib/connectors/mysql-connector.ts:79:22)
    at async Database.query (https://deno.land/x/denodb@v1.0.38/lib/database.ts:240:21)
    at async Function._runQuery (https://deno.land/x/denodb@v1.0.38/lib/model.ts:228:21)
    at async Function.create (https://deno.land/x/denodb@v1.0.38/lib/model.ts:449:21)
    at async createPresent (file:///home/ddorstijn/Documents/Web/trouwerij-deno/controllers/present.ts:24:22)
```
