### ISSUE TITLE
problem with db.sync()

### ISSUE THREAD

**Issue by chovy** [eveningkid/denodb#283]
error: Uncaught (in promise) SqliteError: index email already exists

I have a subscriptions table with email as a field.

Using `db.sync()` causes this error. I'm not sure if I need it. It appears to work without it, but I'm not sure.

Can someone clarify the point of `db.sync()`

**Comment by chovy** [comment]
```
import { Model, DataTypes } from "https://deno.land/x/denodb/mod.ts";
import { db } from '../db.ts';

class Subscriptions extends Model {
  static table = 'subscriptions';
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, default: crypto.randomUUID() },
    email: {
      type: DataTypes.STRING,
      unique: true,
    },
  };
}

db.link([Subscriptions]);
db.sync();

export default Subscriptions
```

This is the code casuing the crash:

```
$ deno run  --allow-all index.ts
Check file:///home/ettinger/www/iptvfish/iptvfish-api/index.ts
error: Uncaught (in promise) TypeError: table[type] is not a function
      instruction = table[type](...fieldNameArgs);
                               ^
    at addFieldToSchema (https://deno.land/x/denodb@v1.0.38/lib/helpers/fields.ts:81:32)
    at TableBuilder._fn (https://deno.land/x/denodb@v1.0.38/lib/translators/sql-translator.ts:152:15)
    at TableBuilder.toSQL (https://raw.githubusercontent.com/aghussb/dex/master/lib/schema/tablebuilder.js:45:12)
    at SchemaCompiler_SQLite3.createTableIfNotExists (https://raw.githubusercontent.com/aghussb/dex/master/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (https://raw.githubusercontent.com/aghussb/dex/master/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (https://raw.githubusercontent.com/aghussb/dex/master/lib/schema/builder.js:81:43)
    at SchemaBuilder.Target.toQuery (https://raw.githubusercontent.com/aghussb/dex/master/lib/interface.js:9:21)
    at SchemaBuilder.toString (https://raw.githubusercontent.com/aghussb/dex/master/lib/schema/builder.js:77:15)
    at SQLTranslator.translateToQuery (https://deno.land/x/denodb@v1.0.38/lib/translators/sql-translator.ts:225:25)
    at SQLite3Connector.query (https://deno.land/x/denodb@v1.0.38/lib/connectors/sqlite3-connector.ts:54:36)
```

**Comment by chovyprognos** [comment]
bump

**Comment by schuelermine** [comment]
This is likely because you have not specified a type for `id`. Try this instead:
```ts
/* … */
    id: {
      ...DataTypes.string(40),
      primaryKey: true
    }
/* … */
```

**Comment by schuelermine** [comment]
That code uses ES spread syntax. If you don’t want to use that, do this:
```
/* … */
    id: {
      type: DataTypes.STRING,
      length: 36,
      primaryKey: true
    }
/* … */
```

**Comment by schuelermine** [comment]
As far as I can tell, the documentation also seems to describe putting defaults in their own static field, like this:
```ts
/* … */
  static defaults = {
    id: "00000000-0000-0000-0000-000000000000"
  }
/* … */
```

**Comment by schuelermine** [comment]
Note that it is likely not a good idea to specify a default ID. While your code may look like it generates a random UUID for every entry, it actually generates one UUID when the model is defined, which is used throughout. It may even be invalid to provide a default primary key.

**Comment by schuelermine** [comment]
> bump

That’s not how GH issues work

**Comment by deadmanwalking74** [comment]
is there any kind of "beforeCreate" hook to populate an id field? or should I do that in my controller.

**Comment by deadmanwalking74** [comment]
I also still get an error with `await db.sync()` -- this feature doesn't seem to work on existing tables...but if i add a table how can I run it?

```
error: SqliteError: index email already exists
    at DB._error (file://$deno$/bundle.js:53139:16)
    at DB.query (file://$deno$/bundle.js:53027:24)
    at file://$deno$/bundle.js:67011:44
    at Array.map (<anonymous>)
    at SQLite3Connector.query (file://$deno$/bundle.js:67010:36)
    at Database1.query (file://$deno$/bundle.js:67301:51)
    at Function.createTable (file://$deno$/bundle.js:65925:38)
    at Database1.sync (file://$deno$/bundle.js:67285:25)
    at file://$deno$/bundle.js:67422:11
```

**Comment by slim-hmidi** [comment]
I have the same issue, `db.sync()` throws an error when `drop ` set to false.

**Comment by DomThePorcupine** [comment]
What is the error you get when you run sync?

**Comment by slim-hmidi** [comment]
I have 3 models `User`, `Product` and `Review`.
I don't want to erase the tables when I start the server because drop set to true removes everything.
with drop: false I got `relation username is already exists`.

username is a column from users table and it contains a constraint to guarantee that is unique.
With all model fields with unique set to true I got this issue.

**Comment by slim-hmidi** [comment]
I think sync() should verify first if the table exists or not then creates it.
Currently without any options it creates the models automatically.

**Comment by DomThePorcupine** [comment]
I think that's what it's doing under the hood (`CREATE IF NOT EXISTS`):

`database.ts`

```js

async sync(options: SyncOptions = {}) {
    if (options.drop) {
      for (let i = this._models.length - 1; i >= 0; i--) {
        await this._models[i].drop();
      }
    }

    ...
    
    for (const model of this._models) {
      await model.createTable();
    }
  }
```

`model.ts`

```js
static async createTable() {
    ....
    const createQuery = this._options.queryBuilder
      .queryForSchema(this)
      .table(this.table)
      .createTable(
        this.formatFieldToDatabase(this.fields) as ModelFields,
        this.formatFieldToDatabase(this.defaults) as ModelDefaults,
        {
          withTimestamps: this.timestamps,
          ifNotExists: true,
        },
      )
      .toDescription();

    await this._options.database.query(createQuery);

   ....
  }
```

I'd be interested to see how I could reproduce the error you're seeing, if you'd care to share some code snippets

**Comment by slim-hmidi** [comment]
I took a look before at that function.
To reproduce the issue you can create those models:
```ts
import { DataTypes, Model } from "https://deno.land/x/denodb@v1.0.40/mod.ts";
import {
  Database,
  PostgresConnector,
} from "https://deno.land/x/denodb@v1.0.40/mod.ts";


class UserModel extends Model {
  static table = "users";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true, type: DataTypes.INTEGER },
    username: { type: DataTypes.STRING, unique: true },
    email: DataTypes.STRING,
    password: DataTypes.STRING,
  };
  }
  
  class ProductModel extends Model {
  static table = "products";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true, type: DataTypes.INTEGER },
    name: { type: DataTypes.STRING, unique: true },
    quantity: DataTypes.INTEGER
  };
}




const connector = new PostgresConnector({
  database: "db",
  host:  "127.0.0.1",
  username: "postgres",
  password: "postgres",
  port:  5432,
});

const db = new Database(connector);


const syncDB = async () => {
  db.link([UserModel, ProductModel])
  await db.sync()
}
```
First time, it will work correctly but if you restart the server or reload it with denon you will get an issue.

**Comment by DomThePorcupine** [comment]
Ah yeah, it looks like the table creation generates two commands:

```
create table if not exists "users" ("id" serial primary key, "username" varchar(255) not null, "email" varchar(255), "password" varchar(255), "created_at" timestamptz not null default CURRENT_TIMESTAMP, "updated_at" timestamptz not null default CURRENT_TIMESTAMP);
```
and
```
alter table "users" add constraint "username" unique ("username")
```

The second one is the one that's failing. Seems like we could check if the constraint already exists before adding it to the query - but I'd guess it'd be easier for denodb to implement some form of migrations instead of building up the sync method...

**Comment by slim-hmidi** [comment]
Thanks for that, so I need to do a workaround to accomplish that until it will be taken into consideration in the future.

**Comment by slim-hmidi** [comment]
I created a migration file to accomplish my task (it's not clean but it does the work) and I think that the sync method is overengineering and contains a lot of logic that makes things not easy to do.
It is better to rethink the design of this function to not contains a lot of details in the background and becomes over abstracted.
