### ISSUE TITLE
SQLite connector inserting empty rows after running single query

### ISSUE THREAD

**Issue by 11** [eveningkid/denodb#293]
### EditL
I miss understood how save works - closing this myself

### Environment
<b>OS:</b> macOS Big Sur - version: 11.5.1
<b>Deno version:</b> deno 1.13.1 (release, x86_64-apple-darwin)
<b>V8 version:</b> v8 9.3.345.11
<b>TS version:</b> typescript 4.3.5

### Issue: 
SQLite connector has a lingering insert query that tries to insert `NULL` data. This empty query seems to always run as the last query.

If it helps - It appears this issue has existed as far back as `v1.0.36`

---

### Example without NULL constraint
create and insert data into a `users` table

#### User Table
```js
class User extends Model {
  static table = 'users'	
  static timestamps = true

  static fields = {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    first: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    last: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: true,
    },
  } 
}
```
#### Insert Logic
```js
async function insert() {
    await db.transaction(async () => {
      const user = await User.create({
        first: 'test',
        last: 'test',
        email: 'test',
      })
      
      await user.save()
    })
}
```

#### Screenshot:
![Screen Shot 2021-08-28 at 4 39 45 PM](https://user-images.githubusercontent.com/6809522/131230509-bdda7aae-3c99-478a-a179-0a9a9d142e81.png)

---

### Adverse effects
This empty query also throws an error if your columns have a `NOT NULL` constraint.

#### User Table:
If I were to update that users model from before to something like:
```js
class User extends Model {
  // .. code from before here
  
  static fields = {
    // ... other fields from before
    first: {
      type: DataTypes.STRING,
      allowNull: false,
    }
  }
}
```

#### Error:
```
$ deno run --import-map=import_map.json --allow-net --allow-env --allow-read --allow-write ./src/index.js
linking db
syncing db
creting insert query
saving to db
SqliteError: NOT NULL constraint failed: users.first
    at DB._error (https://deno.land/x/sqlite@v2.3.1/src/db.ts:289:12)
    at DB.query (https://deno.land/x/sqlite@v2.3.1/src/db.ts:217:20)
    at https://deno.land/x/denodb@v1.0.39/lib/connectors/sqlite3-connector.ts:58:37
    at Array.map (<anonymous>)
    at SQLite3Connector.query (https://deno.land/x/denodb@v1.0.39/lib/connectors/sqlite3-connector.ts:57:32)
    at Database.query (https://deno.land/x/denodb@v1.0.39/lib/database.ts:240:47)
    at Function._runQuery (https://deno.land/x/denodb@v1.0.39/lib/model.ts:228:42)
    at Function.create (https://deno.land/x/denodb@v1.0.39/lib/model.ts:449:32)
    at User.save (https://deno.land/x/denodb@v1.0.39/lib/model.ts:976:41)
    at file:///Users/doug/Code/schoolofthought-backend/src/index.js:42:18
```

#### Screenshot 
When this error is thrown - nothing is inserting into the Database
![Screen Shot 2021-08-28 at 4 50 22 PM](https://user-images.githubusercontent.com/6809522/131230703-6c9c482e-82c9-4acc-b380-9393cbc0076e.png)

**Comment by 11** [comment]
I tried to manually look a bit further into this.

For context I'm working off the latest release `v1.0.39`.

At the moment, I'm printing all the queries that go through `sqlite3-connector.ts - query()` function. 

It seems that the query that tries to insert `NULL`s is related to the default values on a model. If a model doesn't have any specified default values, then the data that gets inserted is NULL. 
```
QUERY: [ "create table if not exists `users` (`id` integer not null primary key autoincrement, `first` varchar..." ]
QUERY:  [ "insert into `users` (`email`, `first`, `last`) values ('test', 'test', 'test')" ]
QUERY:  [ "insert into `users` default values" ]
SqliteError: NOT NULL constraint failed: users.first
    at DB._error (https://deno.land/x/sqlite@v2.3.1/src/db.ts:289:12)
    at DB.query (https://deno.land/x/sqlite@v2.3.1/src/db.ts:217:20)
    at file:///Users/doug/Code/project/src/denodb-test/lib/connectors/sqlite3-connector.ts:59:37
    at Array.map (<anonymous>)
    at SQLite3Connector.query (file:///Users/doug/Code/schoolofthought-backend/src/denodb-test/lib/connectors/sqlite3-connector.ts:58:32)
    at Database.query (file:///Users/doug/Code/schoolofthought-backend/src/denodb-test/lib/database.ts:240:47)
    at Function._runQuery (https://deno.land/x/denodb@v1.0.36/lib/model.ts:228:42)
    at Function.create (https://deno.land/x/denodb@v1.0.36/lib/model.ts:428:32)
    at User.save (https://deno.land/x/denodb@v1.0.36/lib/model.ts:963:41)
    at file:///Users/doug/Code/schoolofthought-backend/src/index.js:42:18
```

When I change the default values on my User model - like so:
```js
class User extends Model {
  static table = 'users'	
  static timestamps = true

  static defaults = {
    first: 'first-name',
    last: 'last-name',
    email: 'test@gmail.com',
  }

  static fields = {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    first: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    last: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    email: {
      type: DataTypes.STRING,
      allowNull: true,
    },
  } 
}
```

the output from this is: 
```
QUERY: [ "create table if not exists `users` (`id` integer not null primary key autoincrement, `first` varchar..." ]
QUERY:  [ "insert into `users` (`email`, `first`, `last`) values ('test', 'test', 'test')" ]
QUERY: [ "insert into `users` (`email`, `first`, `last`) values ('test@gmail.com', 'first-name', 'last-name')" ]
```
