### ISSUE TITLE
Relationships manyToMany throwing error - Foreign key constraint is incorrectly formed

### ISSUE THREAD

**Issue by Netherest** [eveningkid/denodb#296]
Hello!

I've been playing around with denodb and MariaDB trying to setup different types of simple database models.
I've spent the morning trying to debug the error: 
`error: Uncaught (in promise) Error: Can't create table 'deno'.'businesses_owners' (errno: 150 "Foreign key constraint is incorrectly formed")
      throw new Error(error.message);
            ^
    at PoolConnection.nextPacket (https://deno.land/x/mysql@v2.10.0/src/connection.ts:185:13)
    at async PoolConnection.execute (https://deno.land/x/mysql@v2.10.0/src/connection.ts:268:21)
    at async https://deno.land/x/mysql@v2.10.0/src/client.ts:97:14
    at async Client.useConnection (https://deno.land/x/mysql@v2.10.0/src/client.ts:107:14)
    at async Client.execute (https://deno.land/x/mysql@v2.10.0/src/client.ts:96:12)
    at async MySQLConnector.query (https://deno.land/x/denodb@v1.0.39/lib/connectors/mysql-connector.ts:79:22)
    at async Database.query (https://deno.land/x/denodb@v1.0.39/lib/database.ts:240:21)
    at async Function.createTable (https://deno.land/x/denodb@v1.0.39/lib/model.ts:172:5)
    at async Database.sync (https://deno.land/x/denodb@v1.0.39/lib/database.ts:210:7)
    at async file:///E:/test.ts:49:1 `
This error is throwing when using the example code from the manyToMany documentation: https://eveningkid.com/denodb-docs/docs/guides/many-to-many

The error comes up at the `db.sync()` function in the example's code.

If you need more information, happy to provide it.

Cheers,
Angus

**Comment by DavidBonelo** [comment]
I had the same problem and I got this answer https://github.com/eveningkid/denodb/issues/290#issuecomment-907801340

**Comment by boehs** [comment]
Did that resolve the issue
