### ISSUE TITLE
Postgres ENUM resulting in error

### ISSUE THREAD

**Issue by aarongeorge** [eveningkid/denodb#325]
Creating a Model with an ENUM as below causes the following error

```typescript
import { DataTypes, Model } from '../../deps.ts'

class Sample extends Model {
	static table = 'samples'
	static timestamps = true

	static fields = {
		id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
		uuid: { type: DataTypes.UUID },
		filename: { type: DataTypes.STRING },
		creator: { type: DataTypes.UUID },
		tags: { type: DataTypes.ENUM },
		description: { type: DataTypes.STRING }
	}
}

export default Sample
```

```bash
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'join')
        : allowed.join("', '");
                  ^
    at ColumnCompiler_PG.enu (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/dialects/postgres/schema/columncompiler.js:36:19)
    at ColumnCompiler_PG.ColumnCompiler.getColumnType (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/columncompiler.js:84:44)
    at ColumnCompiler_PG.ColumnCompiler.compileColumn (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/columncompiler.js:71:10)
    at ColumnCompiler_PG.ColumnCompiler.toSQL (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/columncompiler.js:59:23)
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/tablecompiler.js:50:51
    at Array.map (<anonymous>)
    at TableCompiler_PG.TableCompiler.create (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/tablecompiler.js:50:34)
    at TableCompiler_PG.TableCompiler.createIfNot (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/tablecompiler.js:63:8)
    at TableCompiler_PG.TableCompiler.toSQL (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/tablecompiler.js:35:20)
    at TableBuilder.toSQL (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/schema/tablebuilder.js:46:42)
```

**Comment by aarongeorge** [comment]
Seems you must provide values to the enums like so:

`tags: { type: DataType.ENUM, values: ['valueOne', 'valueTwo'] }`
