### ISSUE TITLE
Error on use VanillaJS

### ISSUE THREAD

**Issue by DrMcHack** [eveningkid/denodb#331]
Error in SQLTranslator.translateToQuery method:

```
error: Uncaught (in promise) ReferenceError: Buffer is not defined
        } else if (Buffer.isBuffer(val)) {
               ^
    at escapeFn (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/query/string.js:44:16)
    at Client_SQLite3.finalEscape [as _escapeBinding] (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/query/string.js:18:12)
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/client.js:153:19
    at String.replace (<anonymous>)
    at Client_SQLite3._formatQuery (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/client.js:145:16)
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/interface.js:14:28
    at Array.map (<anonymous>)
    at Builder.Target.toQuery (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/interface.js:13:8)
    at Builder.toString (https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/query/builder.js:70:17)
    at SQLTranslator.translateToQuery (https://deno.land/x/denodb@v1.0.40/lib/translators/sql-translator.ts:225:25)

```

**Comment by whhotw** [comment]
You save my life a lot.
