### ISSUE TITLE
Can't import the latest version 1.0.40

### ISSUE THREAD

**Issue by akatechis** [eveningkid/denodb#359]
Dependencies seem to be broken in the latest version. To reproduce:
```typescript
// sample.ts
import * as denodb from "https://deno.land/x/denodb@v1.0.40/mod.ts";
console.log(denodb.Database);
```

```
> deno run sample.ts
Download https://dev.jspm.io/debug@4
Download https://dev.jspm.io/inherits@2.0
Download https://dev.jspm.io/lodash@4
Download https://dev.jspm.io/npm:@jspm/core@1/nodelibs/url.js
Download https://dev.jspm.io/npm:@jspm/core@1/nodelibs/events.js
Download https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js
error: Import 'https://dev.jspm.io/lodash@4' failed: 500 Internal Server Error
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts:13:24
```

**Comment by akatechis** [comment]
If I change the import to point to `1.0.39`, I'm able to import the package.

**Comment by shevernitskiy** [comment]
Currently i had an issue with other dep

```sh
error: Import 'https://dev.jspm.io/debug@4' failed: 500 Internal Server Error
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts:16:23
```

**Comment by codemaster138** [comment]
I can also reproduce this issue, but I have it with `inherits@2.0`...

```
Download https://dev.jspm.io/npm:@jspm/core@1/nodelibs/timers.js
error: Import 'https://dev.jspm.io/inherits@2.0' failed: 500 Internal Server Error
    at https://raw.githubusercontent.com/Zhomart/dex/930253915093e1e08d48ec0409b4aee800d8bd0c/lib-dyn/deps.ts:4:26
```

**Comment by IAmSpudLabs** [comment]
So after some digging in I figured I'd give a full breakdown of what the source of the problem is for anyone else who stumbles on this.

Denodb imports [dex](https://github.com/aghussb/dex) as a dependency to build MySQL queries. The repo Dex (which also appear abandoned) imports multiple files from JSPM. The problem is that JSPM has recently changed their URL format from dev.jspm.io to jspm.dev, which has broken quite a few of Dex's imports.

If anyone would like a fast and easy fix I've forked both denodb and dex to update the import statements using JSPM's new format. [Repo is here](https://github.com/IAmSpudLabs/denodb).

Denodb's unit tests are passing with these changes but the tests appear to only cover sqlite and mysql.

**Comment by osieltorres** [comment]
Check the following answer, as @IAmSpudLabs said, dev.jsmp.dev changed the their URL format and some time ago and some old / out-of-date dependencies does not work anymore. 
The following [comment](https://github.com/eveningkid/denodb/issues/348#issuecomment-1221372635) has a workaround to fix the error.
