### ISSUE TITLE
can not connect mysql

### ISSUE THREAD

**Issue by GGICE** [eveningkid/denodb#61]
InvalidData: data did not match any variant of untagged enum ArgsEnum
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.connect ($deno$/net.ts:182:11)
    at async Connection._connect (https://deno.land/x/mysql/src/connection.ts:45:17)
    at async Connection.connect (https://deno.land/x/mysql/src/connection.ts:82:5)
    at async Client.createConnection (https://deno.land/x/mysql/src/client.ts:45:5)
    at async DeferredStack.pop (https://deno.land/x/mysql/src/deferred.ts:33:20)
    at async Client.useConnection (https://deno.land/x/mysql/src/client.ts:109:24)
    at async Client.execute (https://deno.land/x/mysql/src/client.ts:100:12)
    at async MySQLConnector.query (https://deno.land/x/denodb/lib/connectors/mysql-connector.ts:57:22)

```
deno 1.1.0
v8 8.4.300
typescript 3.9.2
```

**Comment by SquareMesh** [comment]
Hi @GGICE,

I'm using denodb and my connection to mysql is working correctly.  I have done --reload to ensure I'm on latest and my version of deno is same as yours.

Have you tried --reload ?
What version of mysql are you running?
Also, can you show the imports and set up of new Database(), here is mine for reference.

```
const db = new Database('mysql', {
  database: "deno",
  host: "127.0.0.1",
  username: "deno",
  password: "?????????",
});
```

**Comment by GGICE** [comment]
I'm sorry, I miswrote port as a string. It should be a number
