### ISSUE TITLE
Mysql one to one Uncaught Error: Cannot add foreign key constraint

### ISSUE THREAD

**Issue by noodlespan** [eveningkid/denodb#62]
run https://eveningkid.github.io/denodb-docs/docs/guides/one-to-one examle 
throw exception :

INFO connecting 127.0.0.1:3306
INFO connected to 127.0.0.1
error: Uncaught Error: Cannot add foreign key constraint
          throw new Error(error.message);
                ^
    at Connection.nextPacket (https://deno.land/x/mysql/src/connection.ts:95:17)
    at async Connection.execute (https://deno.land/x/mysql/src/connection.ts:162:19)
    at async https://deno.land/x/mysql/src/client.ts:101:14
    at async Client.useConnection (https://deno.land/x/mysql/src/client.ts:111:22)
    at async Client.execute (https://deno.land/x/mysql/src/client.ts:100:12)
    at async MySQLConnector.query (https://deno.land/x/denodb/lib/connectors/mysql-connector.ts:57:22)
    at async Database.query (https://deno.land/x/denodb/lib/database.ts:154:21)
    at async Function.createTable (https://deno.land/x/denodb/lib/model.ts:120:5)
    at async Database.sync (https://deno.land/x/denodb/lib/database.ts:124:7)
    at async file:///E:/deno-practice/practice-15-ORM-one2one/main.ts:55:3

**Comment by eveningkid** [comment]
Hello,

Sorry it took me awhile to get back to this project, I will try to help you as much as I can.

Could you just help me out with some extra debugging please:

1) Try using sqlite **with the same example** and see if the same issue is raised:
```javascript
const db = new Database('sqlite3', {
  filepath: './database.sqlite',
});
```
The rest remains similar. See if this runs properly or not.

2) Run your example again with the debug option turned on and paste the output onto this issue (using MySQL client):
```javascript
const db = new Database({ dialect: 'mysql', debug: true }, ...yourOptions);
```

I should be more reactive this time, so let's fix this together if you're up to it :)

Keep in touch

**Comment by eveningkid** [comment]
Hello,

As I could not get feedback from you, I will close this issue.

Please let me know if this should be reopened, thank you!
