### ISSUE TITLE
Database restart - how to handle

### ISSUE THREAD

**Issue by los-ko** [eveningkid/denodb#63]
Hi!
If im running a OAK server for a long time, and the connection to the DB breaks, how should I handle reconnecting? Should I init a new Database object, and close the old one? Is there a way to check the state of the database object?

This is the error, which I get.
```
BrokenPipe: Broken pipe (os error 32)   
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std@0.51.0/io/bufio.ts:475:25)
    at async Connection._simpleQuery (https://deno.land/x/postgres/connection.ts:280:5)
    at async Connection.query (https://deno.land/x/postgres/connection.ts:546:16)
    at async Client.query (https://deno.land/x/postgres/client.ts:25:12)
    at async PostgresConnector.query (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:46:22)
    at async Database.query (https://deno.land/x/denodb/lib/database.ts:154:21)
```

**Comment by eveningkid** [comment]
Hello,

Thanks for reaching out, that's an odd issue there :)

Well yes, I think this is very independent from denodb as this seems more related to how the connection is handled by clients packages (e.g. mysql client for deno).

> Is there a way to check the state of the database object?

Not to this day and again, it is not provided by the clients I'm using (and any other -_-).

> Should I init a new Database object, and close the old one?

I think this is the only alternative, yes.

From my point of view, your connection should be closed upon `db.close`, not before.
If it does, this is unfortunately related to the way the library behaves internally (and therefore will also happen if you're using these clients independently from denodb).

A good next step would be to go onto [their repo](https://github.com/deno-postgres/deno-postgres) and raise the issue. If they make a library update, this will then be reflected on denodb and solve your issue in a clean way! :)

What do you think?

**Comment by eveningkid** [comment]
I hope you don't mind I close this issue for now.

Again, it might be better asking on their repo as this is not related to denodb itself from my perspective.

If I am wrong, please let me know and we can reopen this issue.

Have a great day
