### ISSUE TITLE
MySQL one-to-one Uncaught error can't create table (errno 150 foreign key constraint is incorrectly formed)

### ISSUE THREAD

**Issue by EktwpMtz** [eveningkid/denodb#75]
(Sorry for my bad English)
I've tried to define a one to one relationship and although it works if I use sqlite it doesn't work if I use MariaDB, this code throws an Uncaught error at db.sync()

```
class Service extends Model {
    static table = "service";
    static timestamps = true;

    static fields = {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
            unique: true,
            allowNull: false
        }
    }
 }

 class Plan extends Model {
    static table = 'plan';
    static timestamps = true;

    static fields = {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
            unique: true,
            allowNull: false
        },
        serviceId: Relationships.belongsTo(Service),
    }

    static service() {
        return this.hasOne(Service);
    }

    public id!: number;
    public serviceId!: number;
 }
 db.link([Service, Plan]);
 await db.sync({ drop: true });
```

**Comment by Frenzoid** [comment]
I see that youre using `serviceId: Relationships.belongsTo(Service)` could you please tell me if the error youre getting is this one?: https://github.com/eveningkid/denodb/issues/76

Best regards.

**Comment by eveningkid** [comment]
Hello Héctor,

Thanks for reporting this issue.

As @Frenzoid mentioned, it would be helpful to get more information regarding your error: what does it say in the console?

Let us know! :)

**Comment by EktwpMtz** [comment]
The console displays this:
```
error: Uncaught Error: can't create tablet `x`.`plan` (errno: 150 "Foreign key constraint is incorrectly formed")
        throw new Error(error.message);
        at Connection.nextPacket (connection.ts:97:17)
        at async Connection.execute(connection.ts:162:19)
        at async client.ts:101:14
        at async Client.useConnection(client.ts:111:22)
        at async Client.execute(client.ts:100:12)
        at async MySQLConnector.query(mysql-connector.ts:57:22)
        at async Database.query(database.ts:154:21)
        at async Function.createTable(model.ts:120:5)
        at async Database.sync(database.ts:124:7)
```
I also checked the error #74  and it's not the same
