### ISSUE TITLE
Uncaught ConnectionRefused: Connection refused (os error 61)

### ISSUE THREAD

**Issue by lizraeli** [eveningkid/denodb#81]
I'm getting this error when trying to link a model and sync the database. I apologize if there's something really basic that I'm missing. This is the code in `db.ts`:
```ts
import { DataTypes, Database, Model } from "https://deno.land/x/denodb/mod.ts";

const db = new Database("postgres", {
  host: "127.0.0.1",
  username: "user",
  password: "",
  database: "conduit",
  port: 5432
});

class User extends Model {
  static table = "users";
  static timestamps = true;

  static fields = {
    id: { primaryKey: true, autoIncrement: true },
    user: { type: DataTypes.STRING, unique: true, required: true },
    email: { type: DataTypes.STRING, unique: true, required: true },
  };
}

db.link([User]);

await db.sync({ drop: true });
```

And this is the error I get when running `deno run --allow-net db.ts`:
```
error: Uncaught ConnectionRefused: Connection refused (os error 61)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:93:10)
    at async Object.connect ($deno$/net.ts:183:11)
    at async Connection.startup (https://deno.land/x/postgres/connection.ts:143:17)
    at async Client.connect (https://deno.land/x/postgres/client.ts:14:5)
    at async PostgresConnector._makeConnection (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:38:5)
    at async PostgresConnector.query (https://deno.land/x/denodb/lib/connectors/postgres-connector.ts:43:5)
    at async Database.query (https://deno.land/x/denodb/lib/database.ts:154:21)
    at async Function.drop (https://deno.land/x/denodb/lib/model.ts:97:5)
    at async Database.sync (https://deno.land/x/denodb/lib/database.ts:119:9)
```

This error does not appear when I remove `db.link([User]);` 
Any help would be appreciated!

**Comment by eveningkid** [comment]
Hello Lev,

Took me awhile to get back to you!

From the error message and stack trace, this seems all related to your database credentials meaning the connection options are apparently wrong. Just double check you got these right (could be the port, hostname...).

It only throws the error when you link `User` because if you don't link any model, then `sync` does not do anything (we can't sync models that were not linked hehe).

I hope this answers your question, just find the right options to connect to your database and you should be alright! :)

Do not hesitate to reopen this if this was not the case.

Have a great weekend!

**Comment by lizraeli** [comment]
Thank you @eveningkid! You were correct that the issue was with my database configuration.
