### ISSUE TITLE
TypeError: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by angel-codes** [eveningkid/denodb#94]
Well, this happens: When I import my database configuration, and I run the server (with the --reload flag) the server starts downloading some modules, and then, the server starts to run and they show the first log (Oak event) and then, they start to download more modules (denodb modules) when the download finishes they throw the same error (log of the promise in database.ts:23).

> Server running in http://localhost:5000
> Download https://deno.land/x/denodb@v1.0.7/unstable_deps.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/mod.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/client.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/collection.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/database.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/result.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/types.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/util.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/ts/type_convert.ts
> Download https://raw.githubusercontent.com/eveningkid/deno_mongo/master/deps.ts
> Download https://deno.land/x/plugin_prepare@v0.6.0/mod.ts
> Download https://deno.land/x/plugin_prepare@v0.6.0/deps.ts
> Download https://deno.land/std@v0.50.0/fs/exists.ts
> Download https://deno.land/std@v0.50.0/log/mod.ts
> Download https://deno.land/std@v0.50.0/path/mod.ts
> Download https://deno.land/std@0.50.0/fs/exists.ts
> Download https://deno.land/std@0.50.0/log/mod.ts
> Download https://deno.land/std@0.50.0/path/mod.ts
> Download https://deno.land/std@0.50.0/log/logger.ts
> Download https://deno.land/std@0.50.0/log/handlers.ts
> Download https://deno.land/std@0.50.0/testing/asserts.ts
> Download https://deno.land/std@0.50.0/log/levels.ts
> Download https://deno.land/std@0.50.0/path/win32.ts
> Download https://deno.land/std@0.50.0/path/posix.ts
> Download https://deno.land/std@0.50.0/path/common.ts
> Download https://deno.land/std@0.50.0/path/separator.ts
> Download https://deno.land/std@0.50.0/path/interface.ts
> Download https://deno.land/std@0.50.0/path/glob.ts
> Download https://deno.land/std@0.50.0/fmt/colors.ts
> Download https://deno.land/std@0.50.0/fs/exists.ts
> Download https://deno.land/std@0.50.0/testing/diff.ts
> Download https://deno.land/std@0.50.0/path/_constants.ts
> Download https://deno.land/std@0.50.0/path/_util.ts
> Download https://deno.land/std@0.50.0/path/_globrex.ts
> Download https://deno.land/std@0.50.0/path/mod.ts
> Check https://deno.land/x/denodb@v1.0.7/unstable_deps.ts
> Something went wrong... TypeError: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
> Type 'URL' is not assignable to type 'string'.
> return new URL(url).pathname
> ~~~
> at https://deno.land/std@0.50.0/path/win32.ts:911:18
> 
> TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
> Type 'URL' is not assignable to type 'string'.
> return new URL(url).pathname;
> ~~~
> at https://deno.land/std@0.50.0/path/posix.ts:433:18
> 
> Found 2 errors.

**Comment by eveningkid** [comment]
Hi Angel,

I just pulled all the commits from `deno_mongo` to update denodb's fork.

Rerun everything using `--reload` in your command and this should fetch the latest version.

Let me know if this fixes your issue!

Have a great day

**Comment by angel-codes** [comment]
Right, I have a different problem, it's a progress. I run my server with the --reload flag, and they start to download all of the modules, the server sends the first log on the terminal (Oak Event). When they start to download the modules of denodb throw the following error

> Check https://deno.land/x/denodb@v1.0.7/unstable_deps.ts
> INFO downloading deno plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/download/v0.10.0/deno_mongo.dll"
> Something went wrong... Error: downloading plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/download/v0.10.0/deno_mongo.dll" failed.
>     at downloadFromRemote (mod.ts:76:11)
>     at async download (mod.ts:46:7)
>     at async prepare (mod.ts:60:21)
>     at async init (util.ts:44:3)
>     at async MongoDBConnector._makeConnection (mongodb-connector.ts:106:7)
>     at async MongoDBConnector.ping (mongodb-connector.ts:121:5)

Do I need anything more?

**Comment by eveningkid** [comment]
This is odd, I need to try this myself. I am busy with all sorts of things but I will find time to test this out asap.

I will get back to you once I have more information, but this seems related to their library from the error code.

Thanks for your patience!

**Comment by angel-codes** [comment]
Any update?
