### ISSUE TITLE
Problem with deno 1.3

### ISSUE THREAD

**Issue by salomontiago** [eveningkid/denodb#97]
I have a windows notebook for development, so, my deno version is 1.3 and when i will sync my db, i receive an error, like:

INFO downloading deno plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/download/v0.10.0/dev0.10.0/deno_mongo.dll"
error: Uncaught Error: downloading plugin "deno_mongo" from "https://github.com/manyuanrong/deno_mongo/releases/downloses/download/v0.10.0/deno_mongo.dll" failed.
    throw Error(`downloading plugin "${name}" from "${remoteUrl}" failed.`);
          ^
    at downloadFromRemote (mod.ts:76:11)
    at async download (mod.ts:46:7)
    at async prepare (mod.ts:60:21)
    at async init (util.ts:44:3)
    at async MongoDBConnector._makeConnection (mongodb-connector.ts:106:7)
    at async MongoDBConnector.query (mongodb-connector.ts:132:5)
    at async Database.query (database.ts:161:21)
    at async Function.createTable (model.ts:117:5)
    at async Database.sync (database.ts:131:7)

I suspect this error is related to a version of "deno_mongo".

**Comment by thang40** [comment]
+1 I've had the same problem, any update?

**Comment by eveningkid** [comment]
Hi Tiago,

I know it's been a long time, thanks for the wait!

If you are still around, I just upgraded to the latest version of `deno_mongo`.

This should have solved the issue.

If not, feel free to comment here and I'll reopen/investigate the issue.

Have a great day!
